# Generated by Django 4.2.1 on 2023-05-08 02:02

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Evento",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=100)),
                (
                    "description",
                    models.CharField(blank=True, max_length=200, null=True),
                ),
                ("date", models.DateField()),
            ],
        ),
        migrations.CreateModel(
            name="Integrante",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=100)),
                ("surname", models.CharField(max_length=100)),
                ("birth_date", models.DateField()),
                (
                    "cellphone",
                    models.CharField(
                        blank=True,
                        max_length=20,
                        null=True,
                        validators=[
                            django.core.validators.RegexValidator("^\\d{1,10}$")
                        ],
                    ),
                ),
                (
                    "is_attending",
                    models.BooleanField(default=False, verbose_name="Representante"),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Parroquia",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=100)),
                ("address", models.CharField(blank=True, max_length=200, null=True)),
            ],
        ),
        migrations.CreateModel(
            name="Mesa",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=100)),
                (
                    "event",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="events.evento"
                    ),
                ),
            ],
            options={
                "unique_together": {("name", "event")},
            },
        ),
        migrations.CreateModel(
            name="Invitado",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "is_present",
                    models.BooleanField(default=False, verbose_name="Esta presente"),
                ),
                (
                    "integrate",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="events.integrante",
                        verbose_name="Integrante",
                    ),
                ),
                (
                    "table",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="events.mesa"
                    ),
                ),
            ],
        ),
        migrations.AddField(
            model_name="integrante",
            name="place",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, to="events.parroquia"
            ),
        ),
        migrations.AlterUniqueTogether(
            name="integrante",
            unique_together={("name", "surname", "birth_date", "place")},
        ),
    ]
